Разметка
htmlacademy-adaptive/2022859-mishka-28 pull request #2
Opened 2023-03-31 13:35 UTC by Yaroslav2769

---
:mortar_board: [Разметка](https://up.htmlacademy.ru/adaptive/28/user/2022859/tasks/4)

2023-04-02 08:09 UTC, summertime-fms requested changes
Что сделано хорошо: 

1. Очень удачно блок с отзывами смешан со слайдером + семантика
2. Футер
3. Форма

Над чем можно поработать/подумать:

1. От части классов можно отказаться и стилизовать от обертки. Это касается случаев когда мы точно уверены что будет такой тег в этом месте всегда (например спан внутри ссылки или dt/dd внутри dl - в таких случаях можно по тегу от обертки, это сократит количество классов в разметке да и в стилях поменьше строк будет
2. На каждом блоке висит класс типа .block__wrapper - ,будет ли тебе удобно писать стили для центрирования каждому блоку отдельно или с этим можно что то сделать?

2023-04-02 08:09 UTC, summertime-fms commented on source/catalog.html
> +<html class="page" lang="ru">
Я бы убрал этот класс так как  этот элемент мы можем стилизовать по тегу. Сам по себе html - корень документа не является компонентом по бэму, это было бы странно. Академия дает это в демках но по сути смысла в этом мало.

2023-04-02 08:09 UTC, summertime-fms commented on source/catalog.html
> +    <nav class="header-menu menu">
Наверное ты имел ввиду header__menu вместо header-menu иначе сейчас у тебя два бэмовских блока на одном элементе. А тут лучше микс сделать.

2023-04-02 08:09 UTC, summertime-fms commented on source/catalog.html
> +          <img class="header__logo-icon" src="img/mishka-logo-mobile.svg" width="86" height="35" alt="Логотип магазина Мишка">
Для микрооптимизаций можно юзать атрибут `decoding="async"`

2023-04-02 08:09 UTC, summertime-fms commented on source/catalog.html
> +          <img class="header__logo-icon" src="img/mishka-logo-mobile.svg" width="86" height="35" alt="Логотип магазина Мишка">
на всех img

2023-04-02 08:09 UTC, summertime-fms commented on source/catalog.html
> +    <section class="hero">
Тут можно просто заголовок оставить так как на секцию это все не тянет

2023-04-02 08:09 UTC, summertime-fms commented on source/catalog.html
> +        <ul class="product-cards__list product-card">
Не согласен со вторым классом. Ты тут хочешь сделать микс - но на списке этого нет смысла делать. А вот на карточке - да. Карточка одновременно часть сетки и самостоятельный компонент который можно где то переиспользовать

2023-04-02 08:09 UTC, summertime-fms commented on source/catalog.html
> +        <ul class="product-cards__list product-card">
и давай сократим класс - просто product

2023-04-02 08:09 UTC, summertime-fms commented on source/catalog.html
> +        <h2 class="production__title production-icon">Процесс<br>производства</h2>
Зачем второй класс?

2023-04-02 08:09 UTC, summertime-fms commented on source/form.html
> +    <section class="form">
Лучше задавать этот класс тегу form потому что вряд ли ты будешь переиспользовать формы вместе вот с этой секцией и текстом ниже. Например если вдруг понадобится засунуть инпут подписки на рассылку в футер, то ты просто возьмешь и поставишь там тег form с инпутом внутри и все стилизуется четко, а так тебе бы пришлось туда вставлять секцию и форму.

2023-04-02 08:09 UTC, summertime-fms commented on source/form.html
> +        <form class="form__auth" action="https://echo.htmlacademy.ru/" method="post">
form просто сделай. А чтобы как то отличать формы внутри страницы (для js например в будущем) можешь использовать атрибут name

2023-04-02 08:09 UTC, summertime-fms commented on source/form.html
> +              <input class="form__input" type="text" name="phone" id="phone">
type tel

2023-04-02 08:09 UTC, summertime-fms commented on source/form.html
> +              <input class="form__input" type="text" name="email" id="email">
type email (не забывай про тайпы)

2023-04-02 08:09 UTC, summertime-fms commented on source/form.html
> +            <textarea class="form__textarea" name="additionally" cols="30" rows="10"></textarea>
лейбла не хватает

2023-04-02 08:09 UTC, summertime-fms commented on source/form.html
> +          <button class="form__button button">Отправить заказа</button>
type submit👿

2023-04-02 08:09 UTC, summertime-fms commented on source/index.html
> +              <span class="hero__lenk-text">Предметы интерьера</span>
Опечатка в классе. Да и не обязательно тут класс спану добавлять, можно будет от ссылки стилизовать по тегу. Но можно и с классом) Кому как удобнее. (я обычно стараюсь поменьше классов использовать где это возможно)

2023-04-02 08:09 UTC, summertime-fms commented on source/index.html
> +              <dt class="product__item-parameter">Цвет</dt>
Тут можно будет по тегу dt и dl
Давай уберем классы а то разметка прям очень пухнет

2023-04-02 08:09 UTC, summertime-fms commented on source/index.html
> +              <p class="advantages__description">Экологически<br>чистые материалы</p>
Можно без параграфа сделать

2023-04-02 08:09 UTC, summertime-fms commented on source/index.html
> +          <a class="reviews-write button" href="">Написать</a>
reviews__write наверное?..

2023-04-02 08:09 UTC, summertime-fms commented on source/index.html
> +                <a class="contacts__link">info@mimimishkashop.ru</a>
href="mailto:<address>"

2023-04-02 08:09 UTC, summertime-fms commented on source/index.html
> +          <a class="contacts-write button" href="#">Напишите нам</a>
contacts__write

2023-04-02 12:47 UTC, Yaroslav2769 commented on source/catalog.html
> +        <h2 class="production__title production-icon">Процесс<br>производства</h2>
Я думал от него иконку вставить

2023-04-02 12:49 UTC, Yaroslav2769 commented on source/index.html
> +              <p class="advantages__description">Экологически<br>чистые материалы</p>
span?

2023-04-03 11:19 UTC, summertime-fms requested changes

2023-04-03 11:19 UTC, summertime-fms commented on source/catalog.html
> +        <h2 class="production__title production-icon">Процесс<br>производства</h2>
Не, давай по модификатору лучше иконку добавлять будем а то иначе получается лишний бэм-блок

2023-04-03 11:27 UTC, merged